name: Latest Blog Posts Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs at midnight UTC daily
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://zerotooneblog.hashnode.dev/rss.xml"
          max_post_count: 5
          readme_path: "README.md"
          template: |
            <table>
              <tr>
                <td width="20%"><img src="$cover_image" width="100%" style="border-radius: 10px;"></td>
                <td width="80%">
                  <a href="$url"><h3>$title</h3></a>
                  <strong>$date</strong><br/>
                  $description
                </td>
              </tr>
            </table>
          committer_username: "blog-bot"
          committer_email: "blog-bot@example.com"
